### ISSUE TITLE
Your Contributions May Need Update

### ISSUE THREAD

**Issue by StanimalTheMan** [nyu-ossd-s19/isaacblinder-weekly#3]
https://piazza.com/class/jr6rrrsgevx3j4?cid=38 has what you can use as a contribution and while I may be incorrect, your contributions.md should be about issues with others' blog posts if anything.  

https://github.com/nyu-ossd-s19/isaacblinder-weekly/blob/gh-pages/contributions.md

**Comment by isaacblinder** [comment]
updating the page, thanks.
